### ISSUE TITLE
Black background hids aerial imagerey

### ISSUE THREAD

**Issue by cliffordsnow** [iandees/tiger-tiles#1]
@iandees  Can the background be changed to transparent so aerial imagery is visible?

**Comment by iandees** [comment]
The background should be transparent. Is it showing as black in the editors?

**Comment by cliffordsnow** [comment]
I'm getting a opaque black background in JOSM.

**Comment by iandees** [comment]
Should be fixed. Looks like a bug in how Mapbox is rendering tiles. I had a Mapbox Satellite layer set to hidden to help with debugging. It wasn't visible when in Mapbox Studio, but was visible when the tiles were rendered to PNGs.

**Comment by cliffordsnow** [comment]
Perfect! Thanks
